const shopActionType = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_ERROR: 'FETCH_COLLECTIONS_ERROR'
};

export default shopActionType;